# Generated by Django 2.2.5 on 2021-01-29 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_book_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_users', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_movie_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_users', to='categories.Category'),
        ),
    ]
