# Generated by Django 2.2.5 on 2021-01-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
