# Generated by Django 2.2.5 on 2021-01-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
